name: Bigyan Bhar, (বিজ্ঞান ভড়)
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
